### ISSUE TITLE
Linux build error = fatal error: RtMidi.h: No such file or directory

### ISSUE THREAD

**Issue by Tetsujinfr** [yvanvds/yse-soundengine#25]
I got the following error at 1% of the build process when trying to build on ubuntu 18.04 (Arm64 CPU):
> /media/tetsfr/SSD/yse-soundengine/YseEngine/synth/../midi/../midi/midiDeviceManager.h:2:10: fatal error: RtMidi.h: No such file or directory
>  #include "RtMidi.h"
>           ^~~~~~~~~~
> compilation terminated.

Here is my cmake output, all looks fine to me:
> yse-soundengine/build$ cmake ..
> -- The C compiler identification is GNU 7.5.0
> -- The CXX compiler identification is GNU 7.5.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
>   The package name passed to `find_package_handle_standard_args` (PkgConfig)
>   does not match the name of the calling package (Portaudio).  This can lead
>   to problems in calling code that expects `find_package` result variables
>   (e.g., `_FOUND`) to follow a certain pattern.
> Call Stack (most recent call first):
>   /usr/local/share/cmake-3.18/Modules/FindPkgConfig.cmake:59 (find_package_handle_standard_args)
>   FindPortaudio.cmake:20 (include)
>   CMakeLists.txt:20 (FIND_PACKAGE)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
> -- Checking for module 'portaudio-2.0'
> --   Found portaudio-2.0, version 19
> -- Found Portaudio: portaudio;asound;m;pthread
> -- Checking for module 'sndfile>=1.0.11'
> --   Found sndfile, version 1.0.28
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /media/tetsfr/SSD/yse-soundengine/build

=> Can you help please ? did I miss a dependency (I have done a `sudo apt-get install librtmidi-dev` but that did not fix the problem)

**Comment by Tetsujinfr** [comment]
Okay, so after a few google search I landed [here](https://www.music.mcgill.ca/~gary/rtmidi/), downloaded the tar.gz file, extracted it and took the RtMidi.h and RtMidi.cpp files from the project root folder and manually copy/pasted them under `/yse-soundengine/midi/` and that fixed the issue above.

Now however I am stuck at 27% of the compilation with the below error in the pSine.cpp source file, which seems more cryptic to solve, help please??
> [ 27%] Building CXX object YseEngine/CMakeFiles/YSE_dlib.dir/patcher/generatorObjects/pSine.cpp.o
> /media/tetsfr/SSD/yse-soundengine/YseEngine/patcher/generatorObjects/pSine.cpp:3:10: fatal error: implementations\logImplementation.h: No such file or directory
>  #include "implementations\logImplementation.h"
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
>

**Comment by Tetsujinfr** [comment]
Okayy, lots of fun installing this.
the second issue and others are caused by some .cpp source files referencing headers path with backward slash "\" instead of forward slash "/". Maybe a windows dev env thing but happening only for a few headers file references, not accross the board, not sure why.

So I ended up modifying in _YseEngine/patcher/generatorObjects/pSine.cpp_ line 3 from `#include "implementations/logImplementation.h"` to `#include "implementations/logImplementation.h"`
and same for _YseEngine/patcher/genericObjects/pDac.cpp_ replacing on line 2 #include "implementations\logImplementation.h"
 by #include "implementations/logImplementation.h"

you are welcome!

**Comment by Tetsujinfr** [comment]
ok so now at approx 39% of the compilation I am stuck again, but this seems like a code error on type declaration vs class available types, not sure, not good enough in cpp.

> yse-soundengine/YseEngine/patcher/patcherImplementation.cpp:247:13: error: prototype for ‘std::size_t YSE::PATCHER::patcherImplementation::Objects()’ does not match any in class ‘YSE::PATCHER::patcherImplementation’
>  std::size_t patcherImplementation::Objects() {
>              ^~~~~~~~~~~~~~~~~~~~~
> In file included from /media/tetsfr/SSD/yse-soundengine/YseEngine/patcher/patcherImplementation.cpp:2:0:
> /media/tetsfr/SSD/yse-soundengine/YseEngine/patcher/patcherImplementation.h:35:20: error: candidate is: unsigned int YSE::PATCHER::patcherImplementation::Objects()
>        unsigned int Objects();
>                     ^~~~~~~
> YseEngine/CMakeFiles/YSE_dlib.dir/build.make:1550: recipe for target 'YseEngine/CMakeFiles/YSE_dlib.dir/patcher/patcherImplementation.cpp.o' failed
> make[2]: *** [YseEngine/CMakeFiles/YSE_dlib.dir/patcher/patcherImplementation.cpp.o] Error 1
> CMakeFiles/Makefile2:135: recipe for target 'YseEngine/CMakeFiles/YSE_dlib.dir/all' failed
> make[1]: *** [YseEngine/CMakeFiles/YSE_dlib.dir/all] Error 2
> Makefile:102: recipe for target 'all' failed
> make: *** [all] Error 2
> 


I wanted hard to try this engine but I am stopping here unfortunately, I am not able to debug the project I am afraid.
@yvanvds if you have an idea, I would love to try it.

bye for now

**Comment by PipeWarp** [comment]
I am experiencing the same issue, a fix would be much appreciated.

**Comment by yvanvds** [comment]
Hi @Tetsujinfr,

Apologies for the long silence — the project was on hiatus and is now being maintained again. v2.1.0 just shipped.

Two things that should resolve your build:

1. The RtMidi backend is now compile-gated behind `YSE_ENABLE_MIDI_DEVICE` (off by default in some build paths). If you don't need device-level MIDI I/O, you can configure with `-DYSE_ENABLE_MIDI_DEVICE=OFF` and avoid the dependency entirely.
2. When it *is* enabled, CMake resolves RtMidi via pkg-config — `sudo apt install librtmidi-dev` on Debian/Ubuntu (you already had that), plus running a recent `pkg-config` so the `.pc` file is found.

Recommended: `python yse.py build` from the repo root — it drives the CMake presets so the dependency resolution is set up correctly.

Closing for hygiene. If v2.1.0 still hits this on your Arm64 Ubuntu, please open a fresh issue with the configure output.
