### ISSUE TITLE
yse_tests_patcher: array.deserialize block-poll test races the parser pool (#797)

### ISSUE THREAD

**Issue by yvanvds** [yvanvds/yse-soundengine#854]
## What happens

`yse_tests_patcher` failed on Linux CI (PR #853, run 31875932212, job "Build and analyze") with a single failed assertion out of 12,075,213:

```
Tests/patcher/test_patcher_array_deserialize.cpp:497: ERROR: CHECK( out.count == 0 ) is NOT correct!
  values: CHECK( 1 == 0 )
```

Failing case: `array.deserialize: the block poll delivers a document sent through the patcher (#797)`.

## Why it is a real defect and not "flaky"

The test encodes a timing assumption that the code does not guarantee:

```cpp
p.PassData(std::string("[60,62,67]"), "doc797m", YSE::T_GUI);
p.Calculate(YSE::T_DSP); // drains the value queue: the submit happens here
ArrayParser().WaitIdle(); // the parse finishes on the pool
CHECK(out.count == 0);   // nothing announced yet — no block has polled
p.Calculate(YSE::T_DSP); // the poll installs and announces
```

`WaitIdle()` is called *after* the first `Calculate(T_DSP)`, so it does not order the background parse against that block. Within that single `Calculate`, the value drain submits the document and the block poll runs afterwards. If the pool finishes parsing `[60,62,67]` before the poll phase of the *same* block, the install and announce happen one block earlier than the test asserts, and `out.count` is already 1 at line 497.

The object's behaviour is fine in both orderings — announcing at the first poll after the parse completes is exactly what it should do. It is the assertion that over-specifies, pinning a scheduling outcome the design never promised.

## Blame

Introduced by 125d029 (`feat(patcher): .array.deserialize — build an array from serialised text (#797)`), which landed in PR #851. It was green there and on the #852 post-merge sweep — a fast parse on a warm pool just had not yet won the race. The batch for #806–#809 (PR #853) adds ~79 patcher test cases ahead of this one, which plausibly changes pool warmth and lets the parse win.

## Suggested fix

Make the assertion depend on the ordering the object actually guarantees rather than on how fast the pool is: either drop the `CHECK(out.count == 0)` line, or restructure so the parse cannot complete before the poll being tested (e.g. assert the final installed state and the announce, and let the "not before the poll" claim be tested by a path that controls the pool). Keep the rest of the case — the installed contents and the `array a797m` announce — as-is.

## Notes

- Real-time / audio-thread path: the test drives `T_DSP`, but the fix is confined to test code.
- Layer: `tests` / `patcher`.
