### ISSUE TITLE
Android build broken on dev: test_device_layer.cpp uses incomplete type DEVICE::managerObject

### ISSUE THREAD

**Issue by yvanvds** [yvanvds/yse-soundengine#622]
### What

The `Android build (arm64-v8a)` and `Android build (x86_64)` jobs in
`.github/workflows/build.yml` have been failing on **every push to `dev`**
since 2026-08-05. This is a compile error, not a timeout — the jobs die at
~3-5 minutes against a 25-minute cap.

```
Tests/system/test_device_layer.cpp:437:42: error: member access into incomplete type 'managerObject'
  437 |     auto& master = YSE::DEVICE::Manager().getMaster();
      |                                          ^
YseEngine/dsp/../device/device.hpp:24:11: note: forward declaration of 'YSE::DEVICE::managerObject'
```

`Tests/system/test_device_layer.cpp` calls `YSE::DEVICE::Manager().getMaster()`,
which needs the complete `YSE::DEVICE::managerObject`. On the desktop
(Linux/PortAudio) build the definition is reached transitively through the
include chain, so the file compiles. On the Android/Oboe build that chain is
different and only the forward declaration in `device.hpp` is visible, so the
member access fails. The test file is missing a direct include of the header
that defines `managerObject`.

### Origin

Introduced by 2fa3ece (`tests: cover the device / audio-IO layer within the
headless CI limits (#418)`, 2026-08-05), which added the file.

It went unnoticed because of the `build-android` trigger gate: that job runs on
pushes to `dev`/`master` and on PRs targeting `master`, but is **skipped on PRs
targeting `dev`**. PR #418 therefore never exercised it, and the breakage only
appeared post-merge on the `dev` push, where nothing gates on it.

### Impact

- Every `dev` push shows a red SonarQube workflow. That normalises a red `dev`
  and will mask the next real regression.
- The next `dev → master` release PR *will* run `build-android` as its release
  gate and will be blocked until this is fixed.

### Suggested fix

Add the direct include for the header defining `YSE::DEVICE::managerObject` to
`Tests/system/test_device_layer.cpp` (include what you use, rather than relying
on the desktop include chain). Confirm against the NDK toolchain, not just the
desktop build.

Worth considering separately: the trigger gate that let this land. A cheap
option is to keep `build-android` skipped on dev-targeted PRs but make the red
`dev` push visible, or to run one ABI on dev PRs when `Tests/` or `YseEngine/`
changes.

### Which surface(s) does this touch?

android, tests

### Layer

android

### Real-time / audio-thread path?

No — build-time only.
